### ISSUE TITLE
Improved variable LFO

### ISSUE THREAD

**Issue by Electrotechnique** [quarterturn/teensy3-ensemble-chorus#3]
Not an issue, but some other developers have done some work on the variable LFO feature that I added and it sounds fantastic now, particularly at low speeds.

[https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/master/TSynth](https://github.com/ElectroTechnique/TSynth-Teensy4.1/tree/master/TSynth)

**Comment by quarterturn** [comment]
Thanks. Do you have a demo somewhere? I'd like to hear it.

**Comment by Electrotechnique** [comment]
Playing with LFO and Mix: [StereoEnsembleDemo.mp3](https://1drv.ms/u/s!Avbtf5PcDsB0i-xFT13JBlTY3shgzQ?e=WoCbjx)

**Comment by quarterturn** [comment]
Hm, onedrive says the file doesn't exist or I don't have access.
